version: '3'
services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        tty: true
        ports:
            - "3000:3000"
        volumes :
            - /app/node_modules
            - .:/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        tty: true
        volumes :
            - /app/node_modules
            - .:/app
        command: ["npm", "test"]
        